export const SUCCESS_UPDATE_USER_ROOTS = 'SUCCESS_UPDATE_USER_ROOTS';
export const FAILURE_UPDATE_USER_ROOTS = 'FAILURE_UPDATE_USER_ROOTS';
export const LOADING_UPDATE_USER_ROOTS = 'LOADING_UPDATE_USER_ROOTS';
